class ExtractionError(ValueError):
    """Errror."""


class NoSourceError(ExtractionError): ...
class UnsupportedFormatError(ExtractionError): ...
class CorruptFileError(ExtractionError): ...
class EmptyTextError(ExtractionError): ...
class SourceFetchError(ExtractionError): ...


class ScannedPdfError(EmptyTextError):
    """pdf kosong"""
